Teste_FitCard/Models/BancoModel.cs
using System.ComponentModel;

namespace Teste_FitCard.Models
{
    public class BancoModel
    {
        [DisplayName("Agência")]
        public string Agencia { get; set; }

        [DisplayName("Conta Corrente")]
        public string Conta { get; set; }
    }
}

Teste_FitCard/Models/CategoriaModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Teste_FitCard.Models
{
    public class CategoriaModel
    {
        
        
        public int IdCategoria { get; set; }

        [MaxLength(100)]
        public string Categoria { get; set; }


    }
}

Teste_FitCard/Models/CidadeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Teste_FitCard.Models
{
    public class CidadeModel
    {
        public string nome { get; set; }

        public int id { get; set; }
    }


}

Teste_FitCard/Models/EnderecoModel.cs
namespace Teste_FitCard.Models
{
    public class EnderecoModel
    {
        public string Logradouro { get; set; }

        public string Cidade { get; set; }

        public string Estado { get; set; }

    }
}

Teste_FitCard/Models/EstabelecimentoModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Teste_FitCard.Models
{
    public class EstabelecimentoModel : PessoaModel
    {
        public int IdEstabelecimento { get; set; }

        [DisplayName("Nome Fantasia")]
        public string NomeFantasia { get; set; }


        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Data de Abertura")]
        public DateTime? DataCadastro { get; set; }

        public CategoriaModel Categoria { get; set; } = new CategoriaModel();

        public string Status { get; set; }

        public BancoModel DadosBancario { get; set; } = new BancoModel();
    }
}

Teste_FitCard/Models/EstadosModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Teste_FitCard.Models
{

    

    public class EstadosModel
    {
        public int id { get; set; }
        public string sigla { get; set; }
        public string nome { get; set; }
        public Regiao regiao { get; set; }
    }

    public class Regiao
    {
        public int id { get; set; }
        public string sigla { get; set; }
        public string nome { get; set; }
    }

}

Teste_FitCard/Models/PessoaModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Permissions;
using System.Web;

namespace Teste_FitCard.Models
{
    public class PessoaModel
    {
        [DisplayName("Nome Razão")]
        [Required(ErrorMessage = "Por favor informe o Nome Razão")]
        public string NomeRazao { get; set; }

       
        [Required(ErrorMessage = "Por favor informe o CNPJ")]
        public string CNPJ { get; set; }

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public string Telefone { get; set; }

        public EnderecoModel Endereco { get; set; } = new EnderecoModel();

    }
}

Teste_FitCard/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Teste_FitCard.Models;
using Teste_FitCard.Repository;

namespace Teste_FitCard.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly CategoriaRepository _cr = new CategoriaRepository();
        // GET: Categoria
        public ActionResult Index()
        {
            return View(_cr.GetCategoria());
        }

        [HttpPost]
        public ActionResult Index(CategoriaModel model)
        {
            try
            {
                _cr.AddOrUpdate(model);

                ViewBag.sucesso = "Dados salvo com sucesso";
            }
            catch (Exception e)
            {
                ViewBag.erro = "ocorreu um problema ao tentar salvar os dados erro";
            }


            return View(_cr.GetCategoria());
        }


        public ActionResult Delete(int id)
        {
            _cr.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Teste_FitCard/Controllers/EstabelecimentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Teste_FitCard.Models;
using Teste_FitCard.Repository;

namespace Teste_FitCard.Controllers
{
    public class EstabelecimentoController : Controller
    {
        private Repository.EstabelecimentoRepository _repository = new EstabelecimentoRepository();

        // GET: Estabelecimento
        public ActionResult Index()
        {
            TempData["ESTABELICIMENTOLIST"] = _repository.GetAll();

            return View();
        }

        public ActionResult AddOrUpdate(string id)
        {
            CarregaCategoria();
            CarregaEstadosECidades();


            var model = new EstabelecimentoModel();
            if (!string.IsNullOrEmpty(id))
            {
                CarregaEstadosECidades();
                model = _repository.GetAll().First(a => a.IdEstabelecimento == Convert.ToInt32(id));

            }




            return View(model);
        }

        [HttpPost]
        public ActionResult AddOrUpdate(EstabelecimentoModel model)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    _repository.AddorUpdate(model);


                    ViewBag.sucesso = "Dados Salvo com sucesso";

                }


            }
            catch (Exception e)
            {
                ViewBag.error = $"Ocorreu um problema ao tentar gravar os dados {e.Message}";

            }

            CarregaCategoria();
            CarregaEstadosECidades();

            return View(new EstabelecimentoModel());
        }

        public ActionResult Delete(int id)
        {
            _repository.Delete(id);

            TempData["ESTABELICIMENTOLIST"] = _repository.GetAll();

            return View("Index");
        }

        private void CarregaCategoria()
        {
            var cat = new CategoriaRepository().GetCategoria();

            TempData["CategoriaList"] = new MultiSelectList(cat, "IdCategoria", "Categoria");
        }

        private void CarregaEstadosECidades()
        {

            var servicos = new Servicos.IGBE_Service();
            var estados = servicos.GetEstados().OrderBy(a => a.nome).ToList();


            Parallel.Invoke(() =>
            {
                var states = new List<SelectListItem>();
                estados.ForEach(item =>
                {
                    states.Add(new SelectListItem { Text = item.nome, Value = item.sigla });

                });

              
                ViewBag.States = states;
            },

                () =>
                {
                    if (Session["CIDADES"] != null) return;

                    var cidades = servicos.GetCidades().ToList();
                    var cidadeList = new List<SelectListItem>();
                    cidades.ForEach(item =>
                    {
                        cidadeList.Add(new SelectListItem { Text = item.nome, Value = item.nome });
                    });

                    Session["CIDADES"] = cidadeList;
                });

        }


        [HttpPost]
        public JsonResult GetCidade(string uf)
        {
            var cidades = new Servicos.IGBE_Service().GetCidades(uf);

            return Json(new SelectList(cidades, "nome", "nome"));
        }


    }
}

Teste_FitCard/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Teste_FitCard.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Teste_FitCard/Views/Categoria/Index.cshtml
@model IEnumerable<Teste_FitCard.Models.CategoriaModel>
@{
    ViewBag.Title = "Index";
}

<h3>Cadastrar/Editar Categorias</h3>

@using (Html.BeginForm("Index", "Categoria", null, FormMethod.Post, new { @class = "", @id = "form-categoria" }))
{

    <div class="form-row">
        <div class="col-md-2 form-group">

            @Html.TextBox("IdCategoria", "", new { @class = "form-control", @readonly = true, placeholder = "Automático" })
        </div>
        <div class="col-md-10">

            <div class="input-group mb-3">

                @Html.TextBox("Categoria", "", new { @class = "form-control", @required = true, placeholder = "Categoria" })
                <div class="input-group-prepend">
                    <button class="btn btn-primary" id="btnSubmit" type="submit">Adicionar</button>
                </div>
                <div id="divCancancelar" class="input-group-prepend d-none">
                    <button class="btn btn-danger" id="btnCancelar" type="button">Cancelar</button>
                </div>
            </div>


        </div>



    </div>


}

<br />

<table id="categorias" class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                Código
            </th>
            <th scope="col">
                Categoria
            </th>
            <th scope="col">
                Ação
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ToList())
        {
            <tr>
                <th scope="row">@item.IdCategoria</th>
                <td>@item.Categoria</td>
                <td>

                    <a href="#" onclick="Editar('@item.IdCategoria','@item.Categoria')" id="edit"><i class="fas fa-edit"></i></a>

                    <a href="@Url.Action("Delete",new{id=@item.IdCategoria})"><i class="fas fa-trash"></i></a>

                </td>
            </tr>
        }
    </tbody>

</table>

<script>
    $(document).ready(function () {

        var sucesso = '@ViewBag.sucesso';
        var erro = '@ViewBag.erro';

        if (sucesso.length > 0) {
            MessageSucess(sucesso);

            $("#IdCategoria").val('');
            $("#Categoria").val('');
        }

        if (erro.length > 0) {
            MessageError(erro);
        }


        $("#btnCancelar").click(function () {
            $("#IdCategoria").val('');
            $("#Categoria").val('');
            document.getElementById("btnSubmit").innerText = "Adicionar";
            $("#divCancancelar").addClass("d-none");

        })

    });

    $("#form-categoria").validate({

        errorPlacement: function () {
            return false;
        },
        rules: {

            Categoria: {
                required: true

            }

        },
        submitHandler: function (form) {

                       form.submit();
        }
    });


    function Editar(idcategoria, categoria) {
        $("#IdCategoria").val(idcategoria);
        $("#Categoria").val(categoria);
        $('#divCancancelar').removeClass("d-none");
        document.getElementById("btnSubmit").innerText = "Atualzar";

    }

</script>

Teste_FitCard/Views/Estabelecimento/AddOrUpdate.cshtml
@model Teste_FitCard.Models.EstabelecimentoModel
@{
    ViewBag.Title = "Cadastro";
    var categorialist = (MultiSelectList)TempData["CategoriaList"];

    IEnumerable<string> status = new List<string> { "Ativo", "Inativo" };

    var listaAtivo = new MultiSelectList(status);

    var states = (List<SelectListItem>)ViewBag.States;

    var cidades = (List<SelectListItem>)Session["CIDADES"];

}

<h3>Cadastro/Editar</h3>


@using (Html.BeginForm("AddOrUpdate", "Estabelecimento", null, FormMethod.Post, new { @id = "form-cadastro", @class = "form-validade" }))
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    @Html.HiddenFor(m => m.IdEstabelecimento)
    <div class="card">
        <div class="card-header"> Dados do Estabelecimento</div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-8 form-group">
                    *@Html.LabelFor(m => m.NomeRazao)
                    @Html.TextBoxFor(m => m.NomeRazao, new { @class = "form-control", @required = true })
                    @Html.ValidationMessageFor(m => m.NomeRazao)
                </div>

                <div class="col-md-4 form-group">
                    *@Html.LabelFor(m => m.CNPJ)
                    @Html.TextBoxFor(m => m.CNPJ, new { @class = "form-control cnpj", @required = true })
                </div>
            </div>

            <div class="row">
                <div class="col-md-8 form-group">
                    @Html.LabelFor(m => m.NomeFantasia)
                    @Html.TextBoxFor(m => m.NomeFantasia, new { @class = "form-control" })

                </div>
                <div class="col-md-4 form-group">
                    *@Html.LabelFor(m => m.Categoria.Categoria)
                    @*@Html.DropDownList("Categoria", null, null, new { @class = "form-control" })*@
                    @Html.DropDownListFor(m => m.Categoria.IdCategoria, new MultiSelectList(categorialist, "Value", "Text"), "--Selecione--", new { @class = "form-control", @required = true })
                    @Html.ValidationMessageFor(m => m.Categoria.Categoria, null, new { @class = "alert-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(m => m.DataCadastro)
                    @Html.TextBoxFor(m => m.DataCadastro, new { @class = "form-control date", @autocomplete = "off" })
                </div>

                <div class="col-md-6 form-group">
                    @Html.LabelFor(m => m.Status)
                    @Html.DropDownListFor(m => m.Status, new MultiSelectList(listaAtivo, "Text", "Text"), "--Selecione--", new { @class = "form-control" })

                </div>
            </div>

            <hr />
            <p><h5>Dados de Contato</h5></p>
            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(m => m.Email)
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @type = "email" })
                </div>

                <div class="col-md-6 form-group">
                    @Html.LabelFor(m => m.Telefone)
                    @Html.TextBoxFor(m => m.Telefone, new { @class = "form-control phone_with_ddd" })
                </div>
            </div>

            <hr />
            <p><h5>Dados de Endereço</h5></p>
            <div class="row">

                <div class="col-md-6 form-group">
                    @Html.LabelFor(m => m.Endereco.Estado)
                    @Html.DropDownListFor(m => m.Endereco.Estado, states, "--Selecione--", new { @class = "form-control estado", @id = "ddlestado" })
                    @*@Html.DropDownListFor(m => m.Endereco.Estado, new MultiSelectList("Estados", "Value", "Text"), new { @class = "form-control" })*@
                </div>

                <div class="col-md-6 form-group">
                    @Html.LabelFor(m => m.Endereco.Cidade)
                    @Html.DropDownListFor(m => m.Endereco.Cidade, cidades, "--Selecione--", new { @class = "form-control", @id = "ddlCidade" })
                    @*@Html.TextBoxFor(m => m.Endereco.Cidade, new { @class = "form-control" })*@
                </div>

            </div>
            <div class="row">
                <div class="col-md-12 form-group">
                    @Html.LabelFor(m => m.Endereco.Logradouro)
                    @Html.TextBoxFor(m => m.Endereco.Logradouro, new { @class = "form-control" })
                </div>
            </div>

            <hr />
            <p><h5>Dados Bancário</h5></p>

            <div class="row">
                <div class="col-md-6 form-group">
                    @Html.LabelFor(m => m.DadosBancario.Agencia)
                    @Html.TextBoxFor(m => m.DadosBancario.Agencia, new { @class = "form-control agencia" })

                </div>
                <div class="col-md-6 form-group">
                    @Html.LabelFor(m => m.DadosBancario.Conta)
                    @Html.TextBoxFor(m => m.DadosBancario.Conta, new { @class = "form-control contacorrente" })
                </div>
            </div>
        </div>
    </div>
    <br />

    <button id="btnSubmit" type="submit" class="btn btn-primary">Confirmar</button>
}

<script>

    $(document).ready(function() {

        var msgError = '@ViewBag.error';
        var msgsucesso = '@ViewBag.sucesso';

        if (msgError.length > 0) {

            //alert(msgError);

            MessageError(msgError);
        }

        if (msgsucesso.length > 0) {
            //alert(msgsucesso);
            MessageSucess(msgsucesso);
        }

        $("#ddlestado").change(function () {

            var uf = $("#ddlestado").val();
            $("#ddlCidade").empty();

            CarregaCidadeS(uf);

        });

    });

    function CarregaCidadeS(uf) {

        $("#ddlCidade").empty();

        $.ajax({
            type: 'POST',
            url: '@Url.Action("GetCidade")',
            dataType: 'json',
            data: { uf: uf },
            success: function (states) {

                $.each(states, function (i, state) {
                    $("#ddlCidade").append('<option value="' + state.Value + '">' +
                        state.Text + '</option>');

                });
            },
            error: function (ex) {
            MessageError("falha para carregar as cidades" + ex)

            }
        });

    }

</script>

Teste_FitCard/Views/Estabelecimento/Index.cshtml
@using Teste_FitCard.Models
@model IEnumerable<Teste_FitCard.Models.EstabelecimentoModel>
@{
    ViewBag.Title = "Index";

    var LISTA = (IEnumerable<EstabelecimentoModel>)TempData["ESTABELICIMENTOLIST"];
}



<h2>Lista de Estabelecimento</h2>

<p class="input-group rounded">
    <input type="search" id="search" class="form-control rounded" placeholder="Pesquisar estabelecimento" aria-label="Search"
           aria-describedby="search-addon" />
    <span class="input-group-text border-0" id="search-addon">
        <i class="fas fa-search"></i>
    </span>
</p>



<table id="estabelecimento" class="table table-striped">
    <thead class="thead-dark">
        <tr class="text-center">


            <th scope="col" class="d-none d-sm-table-cell">
                #
            </th>

            <th scope="col">
                Razão Social
            </th>
            @*<th scope="col">
                    Fantasia
                </th>*@
            <th scope="col">
                CNPJ
            </th>
            @*<th scope="col">
                    E-mail
                </th>*@
            @*<th scope="col">
                    Cidade
                </th>*@
            @*<th scope="col">
                    Estado
                </th>*@
            @*<th scope="col">
                    Telefone
                </th>*@
            <th scope="col" class="d-none d-sm-table-cell">
                Data de Cadastro
            </th>
            <th scope="col" class="d-none d-sm-table-cell">
                Categoria
            </th>
            <th scope="col" class="d-none d-sm-table-cell">
                Status
            </th>
            @*<th scope="col">
                    Agência / Conta
                </th>*@
            <th scope="col">
                Ação
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in LISTA)
        {
            <tr class="text-left font-weight-normal">

                <th scope="row" class="d-none d-sm-table-cell">@item.IdEstabelecimento</th>
                <td>@item.NomeRazao</td>
                <td>@item.CNPJ.FormatCNPJ()</td>
                <td class="text-center d-none d-sm-table-cell">
                    @if (item.DataCadastro != null)
                    {
                        @item.DataCadastro.Value.ToString("dd/MM/yyyy")
                    }


                </td>
                <td class="d-none d-sm-table-cell">@item.Categoria.Categoria</td>
                <td class="d-none d-sm-table-cell">@item.Status</td>


                <td class="text-center">
                    <a href="@Url.Action("AddOrUpdate",new {id=item.IdEstabelecimento})"><i class="fas fa-edit"></i></a>

                    <a class="delete" onclick="ConfirmDelete(@item.IdEstabelecimento)" href="#"><i class="fas fa-trash"></i></a>
                </td>
                <td>
                    <a href="#" data-toggle="modal" data-target="#detail_@item.IdEstabelecimento"><i class="fas fa-search-plus"></i></a>


                    <!-- The Modal -->
                    <div class="modal" id="detail_@item.IdEstabelecimento">
                        <div class="modal-dialog">
                            <div class="modal-content">


                                <div class="modal-header">
                                    <h4 class="modal-title">Detalhes</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">

                                    <div class="row">
                                        <div class="col">
                                            Data Cadastro: @item.DataCadastro
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col">
                                            Telefone: @item.Telefone
                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            Estado: @item.Endereco.Estado
                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            Cidade: @item.Endereco.Cidade
                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            Logradouro: @item.Endereco.Logradouro
                                        </div>

                                    </div>

                                    <div class="row">
                                        <div class="col">
                                            Âgencia: @item.DadosBancario.Agencia
                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            Conta Corrente: @item.DadosBancario.Conta
                                        </div>

                                    </div>
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
                                </div>

                            </div>
                        </div>
                    </div>


                </td>
            </tr>

        }
    </tbody>
</table>

<script>

    $(document).ready(function () {

        $("#search").keyup(function () {

            var value = $(this).val().toLowerCase();

            $("#estabelecimento tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
            });
        });



    });

    function ConfirmDelete(param) {

        bootbox.confirm({
            message: "Você realmente quer excluir registro?",
            buttons: {
                confirm: {
                    label: 'Sim',
                    className: 'btn-success'
                },
                cancel: {
                    label: 'Não',
                    className: 'btn-danger'
                }
            },
            callback: function (result) {

                if (result) {
                    location.href = "/Estabelecimento/Delete/" + param;

                    MessageSucess('registro excluido com sucesso');
                }
                // console.log('This was logged in the callback: ' + result);
            }
        });


        
    };

</script>

Teste_FitCard/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<h2>Bem vindo </h2>

<div class="card">
    <div class="card-header">Atalhos</div>
    <div class="card-body">

        <div class="row text-center">

            <div class="col-md-4">
                <a href="@Url.Action("Index", "Estabelecimento")">
                    <img src="~/Content/img/store_32px.png" />
                    <p>Estabelecimento</p>
                </a>
            </div>
        </div>

    </div>
</div>

Teste_FitCard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FitCart_Teste by Iuris Vidal</title>


    @Styles.Render("~/Content/bundle")
    @Scripts.Render("~/Scripts/bundle")
    
    <script src="https://kit.fontawesome.com/8188cb27f9.js" crossorigin="anonymous"></script>


</head>
<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <a class="navbar-brand" href="/Home">Fit-Card</a>

        <button class="navbar-toggler" type="button"  data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index","Home")">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Estabelecimento")"> Estabelecimento</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Cadastro
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="@Url.Action("AddOrUpdate","Estabelecimento",new{id=""})">Estabelecimento</a>
                        <a class="dropdown-item" href="@Url.Action("Index","Categoria")">Categorias</a>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/iurividal/Teste_FitCard"> GitHub</a>
                </li>

            </ul>
        </div>

    </nav>

    <main role="main" class="container">
        @RenderBody()
        <hr />

        <footer>
            <p>&copy; @DateTime.Now.Year - FitCart_Teste by Iuris Vidal</p>
        </footer>
    </main>

</body>
</html>